name: Setup Java JDK
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Java JDK
        uses: actions/setup-java@v3.14.1
        with:
          java-version: 11
          distribution: adopt
          java-package: jdk
          architecture: x64
          check-latest: true
          server-id: github
          server-username: GITHUB_ACTOR
          server-password: GITHUB_TOKEN
          settings-path: ~/.m2
          overwrite-settings: true
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: $GPG_PASSPHRASE
          cache: maven
          job-status: ${{ job.status }}
          token: ${{ github.server_url == 'https://github.com' && github.token || '' }}
          mvn-toolchain-id: adopt_11
          mvn-toolchain-vendor: adopt

      - name: Build with Gradle
        run: ./gradlew build
