name: Setup Java JDK
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4.7.1
        with:
          java-version: latest
          distribution: 'temurin'
          cache: gradle

      - name: Check for latest JDK version
        uses: actions/setup-java@v4.7.1
        with:
          java-version: latest
          distribution: 'temurin'

      - name: Verify JDK installation (java -version)
        run: java -version

      - name: Verify JDK installation (javac -version)
        run: javac -version

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test

      - name: Verify JDK installation (Gradle task)
        run: ./gradlew printJavaVersion
