name: Setup Gemfile and Deploy Jekyll Site

on:
  push:
    branches:
      - Test-build # Replace 'main' with your default branch if different
  pull_request:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up Ruby environment
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1 # Use a Ruby version compatible with your project
        bundler-cache: true

    # Step 3: Install dependencies from Gemfile
    - name: Install Dependencies
      run: |
        bundle config set path 'vendor/bundle'
        bundle install

    # Step 4: Validate the Gemfile installation
    - name: Validate Installation
      run: |
        if [ -f "Gemfile.lock" ]; then
          echo "Gemfile installed successfully!"
        else
          echo "Error: Gemfile.lock not found!" && exit 1

    # Step 5: Build the Jekyll site
    - name: Build Jekyll Site
      run: bundle exec jekyll build

    # Step 6: Deploy the built site to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
