# Workflow to build and deploy a Jekyll site to GitHub Pages
name: Deploy Jekyll Site to GitHub Pages

on:
  # Trigger on pushes to the Test-build branch
  push:
    branches: ["Test-build"]

  # Allow manual runs from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  JEKYLL_ENV: production # Set environment to production for Jekyll builds

jobs:
  # Build the Jekyll site
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1' # Ensure Ruby version is compatible with Jekyll

      - name: Cache Ruby Gems
        uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Install Jekyll and Bundler
        run: |
          gem install bundler
          bundle install --path vendor/bundle

      - name: Build Jekyll Site
        run: bundle exec jekyll build --destination ./_site

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site

  # Deploy to GitHub Pages
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Notify on Successful Deployment
        if: success()
        run: echo "Deployment to GitHub Pages was successful!"
